trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: "Infra and Artifact Build Stage"
  jobs:
    - job: ArtifactBuild
      steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '20.x'
      
      - script: |
          cd $(build.sourcesdirectory)
          npm install -g @angular/cli
          npm install
          ng build
        displayName: "npm install and build"
        workingDirectory: '$(build.sourcesdirectory)'
      
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: 'latest'
      
      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(build.sourcesdirectory)/env'
          backendServiceArm: 'Pay-As-You-Go(1)(a355c32e-4a22-4b05-aab4-be236850fa6e)'
          backendAzureRmResourceGroupName: 'NextOps'
          backendAzureRmStorageAccountName: 'nextopstfsat19'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'DEV/dev.tfstate'
      
      - task: TerraformTaskV2@2
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: 'env'
          commandOptions: '--auto-approve'
          environmentServiceNameAzureRM: 'Pay-As-You-Go(1)(a355c32e-4a22-4b05-aab4-be236850fa6e)'